name: Docker Image CI for UniProt MCP Server 

on:
  push:
    branches: [ "readme_live" ]
  pull_request:
    branches: [ "readme_live" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: docker build . --file Dockerfile --tag uniprot-mcp-server:$(date +%s)
