name: Docker Image CI for UniProt MCP Server 

on:
  push:
    branches: [ "readme_live" ]
  pull_request:
    branches: [ "readme_live" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker login --username ebi-uniprot --password ${{ secrets.GH_PAT }} ghcr.io
        docker buildx build --platform linux/amd64,linux/arm64 --tag ghcr.io/ebi-uniprot/uniprot-mcp-server:latest .
        docker push ghcr.io/ebi-uniprot/uniprot-mcp-server:latest
